### PR TITLE
dr4st1c WIP

### PR DESCRIPTION
**Pull request by npaladin2000**
Add 32 bit libraries for DraStic, config file to be copied to DraStic directory after install, and Drastic fetch/unzip script to install DraStic.

### CODE REVIEW

**Comment by valadaa48** [comment]
where do all of these files go?

**Comment by valadaa48** [comment]
lib32-compat updated with new lib

**Comment by npaladin2000** [comment]
The drastic config files can go in ~, that's where the script expects them to be waiting for the copy command. Not sure where you want to put the installer script.   armhf-32 goes in /usr/lib, and 00-lib32-compat.conf goes in /etc/ld.so.conf.d/.  Wasn't sure how to lay them out in here, they'll probably need to be moved around.

**Comment by npaladin2000** [comment]
Too old, too many conflicts, starting over

**Pull request closed without merging**
